# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApiGenCli < Formula
  desc ""
  homepage "https://github.com/victormazeli/homebrew-tools"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.4/api-gen-cli_Darwin_x86_64.tar.gz"
      sha256 "9b4ec730ae59eff1197860e2e320f6d04e7d4e886ff7db24710fe87d7067ef2d"

      def install
        bin.install "api-gen-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.4/api-gen-cli_Darwin_arm64.tar.gz"
      sha256 "cf1cea069e7b0e7b4da2cfd129bbe0f2fa8fbdc8c68cdc9e542286a07c948543"

      def install
        bin.install "api-gen-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.4/api-gen-cli_Linux_x86_64.tar.gz"
      sha256 "2ea31ef44f9b02993359011e4a5435653030918a2df59585b7e60b6856bc6a58"

      def install
        bin.install "api-gen-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.4/api-gen-cli_Linux_arm64.tar.gz"
      sha256 "f855036e1596dcbc05c04ad948b1362d2bb4f3a947d21e52e32714bade4374fb"

      def install
        bin.install "api-gen-cli"
      end
    end
  end
end
