# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApiGenCli < Formula
  desc ""
  homepage "https://github.com/victormazeli/homebrew-tools"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.9/api-gen-cli_Darwin_x86_64.tar.gz"
      sha256 "5b2e0584288b8bbf5734e1096b649872c995c0aacdb170d00fb2509a1e1b4a22"

      def install
        bin.install "api-gen-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.9/api-gen-cli_Darwin_arm64.tar.gz"
      sha256 "a0866859150c24e786aae4e1e427a9908000c8a522d3f5135d8e0610a231201d"

      def install
        bin.install "api-gen-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.9/api-gen-cli_Linux_x86_64.tar.gz"
      sha256 "6f357c899b469ef4a102953505ae780ddf3396ba60ec8d5da44b29855b03a377"

      def install
        bin.install "api-gen-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/victormazeli/api-gen-cli/releases/download/v0.1.9/api-gen-cli_Linux_arm64.tar.gz"
      sha256 "909685e733acb34b00348592fb43958df550d746f27ae3d4692f58734bbdbbe8"

      def install
        bin.install "api-gen-cli"
      end
    end
  end
end
